/**
 * 传记成片步骤编号（含 shared prep 10–80 与传记专有 90–260）。
 */
export {
  VIDEO_PREP_STEPS,
  VIDEO_PREP_ERA_LANE_STEP_IDS,
  VIDEO_PREP_PERSONAL_LANE_STEP_IDS,
  VIDEO_PREP_ALL_STEP_IDS,
  stepPipelineFilename,
  stepPromptFilename,
} from "../../shared/constants/prepStepIds.js";

import {
  VIDEO_PREP_ALL_STEP_IDS,
  VIDEO_PREP_STEPS,
} from "../../shared/constants/prepStepIds.js";

export const VIDEO_PIPELINE_STEPS = {
  ...VIDEO_PREP_STEPS,
  SUBSCENE_SPLIT: "90",
  LIVING_CONTEXT: "100",
  ENV_NARRATIVE: "110",
  SCENE_EMBELLISH: "120",
  NAME_UNIFY: "130",
  PHASE_REPLACE: "140",
  MERGE: "150",
  VOICEOVER: "160",
  VOICEOVER_COHERENCE: "170",
  TTS: "180",
  VISUAL_CREATE: "190",
  VISUAL_EXPAND: "200",
  STYLE_PREFIX: "210",
  STYLE_USER_PLACE: "220",
  GEO_SIGNAGE: "230",
  TEXT2IMG: "240",
  VIDEO_CLIPS: "250",
  MERGE_VIDEO: "260",
} as const;

export type VideoPipelineStepId = (typeof VIDEO_PIPELINE_STEPS)[keyof typeof VIDEO_PIPELINE_STEPS];

/** 传记在 shared prep（80）之后继续的个人线步。 */
export const VIDEO_BIOGRAPHY_POST_PREP_PERSONAL_LANE_STEP_IDS = [
  VIDEO_PIPELINE_STEPS.SUBSCENE_SPLIT,
  VIDEO_PIPELINE_STEPS.LIVING_CONTEXT,
  VIDEO_PIPELINE_STEPS.ENV_NARRATIVE,
  VIDEO_PIPELINE_STEPS.SCENE_EMBELLISH,
] as const;

export const VIDEO_BIOGRAPHY_MERGE_LANE_STEP_IDS = [
  VIDEO_PIPELINE_STEPS.NAME_UNIFY,
  VIDEO_PIPELINE_STEPS.PHASE_REPLACE,
  VIDEO_PIPELINE_STEPS.MERGE,
  VIDEO_PIPELINE_STEPS.VOICEOVER,
  VIDEO_PIPELINE_STEPS.VOICEOVER_COHERENCE,
  VIDEO_PIPELINE_STEPS.TTS,
  VIDEO_PIPELINE_STEPS.VISUAL_CREATE,
  VIDEO_PIPELINE_STEPS.VISUAL_EXPAND,
  VIDEO_PIPELINE_STEPS.STYLE_PREFIX,
  VIDEO_PIPELINE_STEPS.STYLE_USER_PLACE,
  VIDEO_PIPELINE_STEPS.GEO_SIGNAGE,
  VIDEO_PIPELINE_STEPS.TEXT2IMG,
  VIDEO_PIPELINE_STEPS.VIDEO_CLIPS,
  VIDEO_PIPELINE_STEPS.MERGE_VIDEO,
] as const;

export const VIDEO_BIOGRAPHY_LANE_STEP_IDS = [
  ...VIDEO_BIOGRAPHY_POST_PREP_PERSONAL_LANE_STEP_IDS,
  ...VIDEO_BIOGRAPHY_MERGE_LANE_STEP_IDS,
] as const;

export const VIDEO_BIOGRAPHY_PIPELINE_STEP_IDS = [
  ...VIDEO_PREP_ALL_STEP_IDS,
  ...VIDEO_BIOGRAPHY_LANE_STEP_IDS,
] as const;
